[client]
httpRequestTimeout = 1000000
[token]
baseURL = "https://localhost:9443"
restVersion = "v0.14"
dcrVersion = "v0.14"
publisherEndpoint = "{baseURL}/api/am/publisher/{restVersion}"
adminEndpoint = "{baseURL}/api/am/admin/{restVersion}"
registrationEndpoint = "{baseURL}/client-registration/{dcrVersion}/register"
tokenEndpoint = "{baseURL}/oauth2/token"
username = "admin"
clientId = "PsIUk9KmpK5zQNE8h8VmcktVF9wa"
clientSecret = "6aOM289G2dQm7rdWfhuPS+RzXQnNDmRrd0s6JdCDTrajoALStf4J4pEFihInvUfA"
trustStoreLocation = "/Users/viraj/Documents/APIM-2/resolve_merge/viraj_4/rcPacks/wso2am-micro-gw-toolkit-macos-3.1.0/lib/platform/bre/security/ballerinaTruststore.p12"
trustStorePassword = "szeswfB8SMyPMW4vZkBjiUW+PKK/lV8ykPC8x04BSQk="
[corsConfiguration]
accessControlAllowOrigins = ["*"]
accessControlAllowCredentials = false
corsConfigurationEnabled = false
accessControlAllowHeaders = ["authorization", "Access-Control-Allow-Origin", "Content-Type", "SOAPAction"]
accessControlAllowMethods = ["GET", "PUT", "POST", "DELETE", "PATCH", "OPTIONS"]
